service: hit-counter
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource:
        - "*"
  memorySize: 128

functions:
  apps:
    handler: index.handler
    timeout: 6
    events: 
      - http: 
          path: /user
          method: post
      - http: 
          path: /verifyPlayer
          method: get
      - http: 
          path: /signOn
          method: post
      - http: 
          path: /verifyToken
          method: get
      - http: 
          path: /allGameType
          method: get
      - http: 
          path: /gameConfig
          method: get
      - http: 
          path: /startGame
          method: post
      - http: 
          path: /gameOver
          method: post
      - http: 
          path: /gameOver
          method: options
  

